// <auto-generated />
namespace Repozytorium.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pole_wymagane_dla_typu_funduszu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pole_wymagane_dla_typu_funduszu));
        
        string IMigrationMetadata.Id
        {
            get { return "201603040525476_pole_wymagane_dla_typu_funduszu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
