// <auto-generated />
namespace Repozytorium.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FundOplataTyp_Dodanie_Nowych_Atrybutow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FundOplataTyp_Dodanie_Nowych_Atrybutow));
        
        string IMigrationMetadata.Id
        {
            get { return "201603060603244_FundOplataTyp_Dodanie_Nowych_Atrybutow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
