// <auto-generated />
namespace Repozytorium.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class zmiany_dla_azure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zmiany_dla_azure));
        
        string IMigrationMetadata.Id
        {
            get { return "201608091736072_zmiany_dla_azure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
